#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#include <vmsys.h>

typedef VMINT(*vm_get_sym_entry_t)(char* symbol);
extern vm_get_sym_entry_t vm_get_sym_entry;


enum bt_obex_events{
	MSG_ID_GOEP_REGISTER_SERVER_REQ,
	MSG_ID_GOEP_REGISTER_SERVER_RSP,
	MSG_ID_GOEP_DEREGISTER_SERVER_REQ,
	MSG_ID_GOEP_DEREGISTER_SERVER_RSP,
	MSG_ID_GOEP_CONNECT_IND,
	MSG_ID_GOEP_CONNECT_RES,
	MSG_ID_GOEP_PUSH_IND,
	MSG_ID_GOEP_PUSH_RES,
	MSG_ID_GOEP_PULL_IND,
	MSG_ID_GOEP_PULL_RES,
	MSG_ID_GOEP_SET_FOLDER_IND,
	MSG_ID_GOEP_SET_FOLDER_RES,
	MSG_ID_GOEP_ABORT_IND,
	MSG_ID_GOEP_ABORT_RES,
	MSG_ID_GOEP_AUTH_REQ,
	MSG_ID_GOEP_AUTH_RSP,
	MSG_ID_GOEP_REGISTER_CLIENT_REQ,
	MSG_ID_GOEP_REGISTER_CLIENT_RSP,
	MSG_ID_GOEP_DEREGISTER_CLIENT_REQ,
	MSG_ID_GOEP_DEREGISTER_CLIENT_RSP,
	MSG_ID_GOEP_CONNECT_REQ,
	MSG_ID_GOEP_CONNECT_RSP,
	MSG_ID_GOEP_PUSH_REQ,
	MSG_ID_GOEP_PUSH_RSP,
	MSG_ID_GOEP_PULL_REQ,
	MSG_ID_GOEP_PULL_RSP,
	MSG_ID_GOEP_SET_FOLDER_REQ,
	MSG_ID_GOEP_SET_FOLDER_RSP,
	MSG_ID_GOEP_ABORT_REQ,
	MSG_ID_GOEP_ABORT_RSP,
	MSG_ID_GOEP_DISCONNECT_REQ,
	MSG_ID_GOEP_DISCONNECT_RSP,
	MSG_ID_GOEP_DISCONNECT_IND,
	MSG_ID_GOEP_DISCONNECT_RES,
	MSG_ID_GOEP_TPDISCONNECT_REQ,
	MSG_ID_GOEP_AUTH_IND,
	MSG_ID_GOEP_AUTH_RES,
	MSG_ID_GOEP_OPP_SUPPORTED_FORMATS_IND,
	MSG_ID_GOEP_AUTHORIZE_IND,
	MSG_ID_GOEP_AUTHORIZE_RES,
};

VMBOOL bt_opp_pre_init();

#ifdef __cplusplus
}
#endif